-- item_listing table seeds here (Example)
INSERT INTO item_listing (title, description, price, image_url, is_available, user_id) VALUES ('Laptop', 'Brand new laptop with high-performance specifications', 999.99, 'https://source.unsplash.com/800x600/?laptop', true, 1);
INSERT INTO item_listing (title, description, price, image_url, is_available, user_id) VALUES ('Smartphone', 'Latest model smartphone with advanced features', 599.99, 'https://source.unsplash.com/800x600/?smartphone', true, 2);
INSERT INTO item_listing (title, description, price, image_url, is_available, user_id) VALUES ('Coffee Maker', 'Premium coffee maker for brewing delicious coffee', 79.99, 'https://source.unsplash.com/800x600/?coffeemaker', true, 3);
INSERT INTO item_listing (title, description, price, image_url, is_available, user_id) VALUES ('Fitness Tracker', 'Water-resistant fitness tracker with heart rate monitor', 49.99, 'https://source.unsplash.com/800x600/?fitnesstracker', true, 1);
INSERT INTO item_listing (title, description, price, image_url, is_available, user_id) VALUES ('Bluetooth Earbuds', 'Wireless Bluetooth earbuds for immersive audio experience', 29.99, 'https://source.unsplash.com/800x600/?earbuds', true, 4);
INSERT INTO item_listing (title, description, price, image_url, is_available, user_id) VALUES ('Gaming Mouse', 'High-precision gaming mouse with customizable buttons', 39.99, 'https://source.unsplash.com/800x600/?gamingmouse', true, 2);
INSERT INTO item_listing (title, description, price, image_url, is_available, user_id) VALUES ('Bookshelf', 'Sturdy wooden bookshelf with multiple shelves', 129.99, 'https://source.unsplash.com/800x600/?bookshelf', true, 3);
INSERT INTO item_listing (title, description, price, image_url, is_available, user_id) VALUES ('Smart Watch', 'Smartwatch with fitness tracking and notification feature', 89.99, 'https://source.unsplash.com/800x600/?smartwatch', true, 4);
INSERT INTO item_listing (title, description, price, image_url, is_available, user_id) VALUES ('Portable Speaker', 'Compact portable speaker with Bluetooth connectivity', 59.99, 'https://source.unsplash.com/800x600/?speaker', true, 1);
INSERT INTO item_listing (title, description, price, image_url, is_available, user_id) VALUES ('Desk Chair', 'Ergonomic desk chair for comfortable long hours of work', 149.99, 'https://source.unsplash.com/800x600/?deskchair', true, 2);
